{{- if .Values.adapter.enabled }}
{{- $adapterName := printf "%s-adapter" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- $adapterServiceName := printf "%s-adapter" (include "common.names.name" .) | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $adapterServiceName }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ $adapterName }}
spec:
  type: {{ .Values.adapter.service.type }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $adapterName }}
  ports:
    - name: http
      port: {{ .Values.adapter.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
