{{- if or .Values.postgresql.enabled (index .Values "postgresql-ha" "enabled") }}
{{- $conn := "" }}
{{- if .Values.postgresql.enabled }}
{{- $conn = printf "postgresql://%s:%s@%s:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password .Values.postgresql.fullnameOverride .Values.postgresql.auth.database }}
{{- else if (index .Values "postgresql-ha" "enabled") }}
{{- $conn = printf "postgresql://%s:%s@%s-%s:5432/%s" (index .Values "postgresql-ha" "postgresql" "username") (index .Values "postgresql-ha" "postgresql" "password") .Release.Name (index .Values "postgresql-ha" "postgresqlExternalHost") (index .Values "postgresql-ha" "postgresql" "database") }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-connection-url
type: Opaque
data:
  POSTGRES_CONNECTION_URL: {{ $conn | b64enc | quote }}
{{- end }}