#!/bin/sh
set -e
export INSTALL_DIR="/tmp"

echo "[HOOK] Running betterleaks (merge)..."

# Ensure installed
./.githooks/install-betterleaks.sh

# Run scan on the merge result staged in the index
if $INSTALL_DIR/betterleaks git --staged --verbose; then
  git config --local betterleaks-status.var "passed"
  echo "betterleaks passed"
else
  git config --local betterleaks-status.var "failed"
  echo "Secret detected. Please review the output above and remove any secrets before completing the merge."
  exit 1 # Comment this line if use detect mode
fi
