apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
{{- range $name, $block := .Values.config }}
  {{ $name }}.yml: |
{{ include "redfish-exporter.config.yml" $block | b64enc | indent 4 }}
{{- end }}