apiVersion: v1
kind: Service
metadata:
  name: go-backend
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.go_backend.service.port }}
    protocol: TCP
    targetPort: 4000
  selector:
    app: go-backend
  type: ClusterIP

