apiVersion: v1
data:
  seed-state.yaml: |-
    {
      "State": [
        {
          "ID": 1,
          "Name": "Ok",
          "Order": 0,
          "Payload": '{{ .Files.Get "files/payload-ok.json" | nindent 10 }}',
          "IsAbnormal": false
        },
        {
          "ID": 2,
          "Name": "Warning",
          "Order": 0,
          "Payload": '{{ .Files.Get "files/payload-warning.json" | nindent 10 }}',
          "IsAbnormal": false
        },
        {
          "ID": 3,
          "Name": "Critical",
          "Order": 0,
          "Payload": '{{ .Files.Get "files/payload-critical.json" | nindent 10 }}',
          "IsAbnormal": false
        },
        {
          "ID": 4,
          "Name": "Down",
          "Order": 0,
          "Payload": '{{ .Files.Get "files/payload-down.json" | nindent 10 }}',
          "IsAbnormal": false
        },
        {
          "ID": 5,
          "Name": "Unknown",
          "Order": 0,
          "Payload": '{{ .Files.Get "files/payload-unknown.json" | nindent 10 }}',
          "IsAbnormal": false
        }
      ]
    }
kind: ConfigMap
metadata:
  name: seed-state-config
  namespace: {{ .Values.namespace }}