apiVersion: v1
kind: ConfigMap
data:
  seed-template.yaml: |-
    {
      "Template": [
        {
          "ID": 1,
          "Name": "Default",
          "Order": 0,
          "Payload": '{{ .Files.Get "files/seed-template-payload.json" | indent 12 }}',
          "IsGlobal": false,
          "Default": false
        }
      ]
    }
metadata:
  name: seed-template-config
  namespace: {{ .Values.namespace }}