apiVersion: v1
data:
  BACKEND_URL: "{{ .Values.go_backend.configmap.data.BACKEND_URL }}"
  DATABASE_URL: "{{ .Values.go_backend.configmap.data.DATABASE_URL }}"
  FRONTEND_URL: "{{ .Values.go_backend.configmap.data.FRONTEND_URL }}"
  PORT: "{{ .Values.go_backend.configmap.data.PORT }}"
  REDIS_ADDR: "{{ .Values.go_backend.configmap.data.REDIS_ADDR }}"
  REDIS_ADDRESS: "{{ .Values.go_backend.configmap.data.REDIS_ADDRESS }}"
  UPLOAD_DIR: "{{ .Values.go_backend.configmap.data.UPLOAD_DIR }}"
  PERMISSIONS_ENABLED:  "{{ .Values.go_backend.configmap.data.PERMISSIONS_ENABLED }}"
  TRAEFIK_TEMPLATE: "{{ .Values.go_backend.configmap.data.TRAEFIK_TEMPLATE }}"

kind: ConfigMap
metadata:
  name: go-backend-conf
  namespace: {{ .Values.namespace }}
