apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-backend
    spec:
      initContainers:
      - command:
        - sh
        - -c
        - ../server -migrate -seed /opt/seed-group.yaml -seed /opt/seed.yaml -seed /opt/seed-dashboard.yaml -seed /opt/seed-datasource.yaml -seed /opt/seed-query.yaml -seed /opt/seed-state.yaml -seed /opt/seed-template.yaml -seed /opt/seed-icon.yaml
        envFrom:
        - configMapRef:
            name: go-backend-conf
            optional: false
        image: {{ template "go_backend_image" . }}
        imagePullPolicy: {{ .Values.go_backend.deployment.image.pullPolicy }}
        name: init-seed
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: seed-config
          mountPath: /opt/seed.yaml
          subPath: seed.yaml
        - name: seed-group-config
          mountPath: /opt/seed-group.yaml
          subPath: seed-group.yaml
        - name: seed-dashboard-config
          mountPath: /opt/seed-dashboard.yaml
          subPath: seed-dashboard.yaml
        - name: seed-datasource-config
          mountPath: /opt/seed-datasource.yaml
          subPath: seed-datasource.yaml
        - name: seed-query-config
          mountPath: /opt/seed-query.yaml
          subPath: seed-query.yaml
        - name: seed-state-config
          mountPath: /opt/seed-state.yaml
          subPath: seed-state.yaml
        - name: seed-template-config
          mountPath: /opt/seed-template.yaml
          subPath: seed-template.yaml
        - name: seed-icon-config
          mountPath: /opt/seed-icon.yaml
          subPath: seed-icon.yaml
        - name: traefik-config
          mountPath: "{{ .Values.go_backend.configmap.data.TRAEFIK_TEMPLATE }}"
          subPath: "{{ base .Values.go_backend.configmap.data.TRAEFIK_TEMPLATE }}"
      containers:
      - args:
        - -migrate
        - -worker
        command:
        - /server
        envFrom:
        - configMapRef:
            name: go-backend-conf
            optional: false
        image: {{ template "go_backend_image" . }}
        imagePullPolicy: {{ .Values.go_backend.deployment.image.pullPolicy }}
        name: worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - envFrom:
        - configMapRef:
            name: go-backend-conf
            optional: false
        image: {{ template "go_backend_image" . }}
        imagePullPolicy: {{ .Values.go_backend.deployment.image.pullPolicy }}
        name: app
        args:
        - -migrate
        - -server
        command:
        - /server
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: go-backend-persistent-storage
        - name: traefik-config
          mountPath: "{{ .Values.go_backend.configmap.data.TRAEFIK_TEMPLATE }}"
          subPath: "{{ base .Values.go_backend.configmap.data.TRAEFIK_TEMPLATE }}"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: "{{ .Values.image.pullSecret }}"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: seed-config
        configMap:
          defaultMode: 420
          name: seed-config
      - name: seed-group-config
        configMap:
          defaultMode: 420
          name: seed-group-config
      - name: seed-dashboard-config
        configMap:
          defaultMode: 420
          name: seed-dashboard-config
      - name: seed-datasource-config
        configMap:
          defaultMode: 420
          name: seed-datasource-config
      - name: seed-query-config
        configMap:
          defaultMode: 420
          name: seed-query-config
      - name: seed-state-config
        configMap:
          defaultMode: 420
          name: seed-state-config
      - name: seed-template-config
        configMap:
          defaultMode: 420
          name: seed-template-config
      - name: seed-icon-config
        configMap:
          defaultMode: 420
          name: seed-icon-config
      - name: go-backend-persistent-storage
        hostPath:
          path: {{ .Values.global.basePath}}/{{ .Release.Namespace }}/upload_data_newtopo
          type: DirectoryOrCreate
      - name: traefik-config
        configMap:
          name: traefik-template-conf
          items:
            - key: traefik_config_template.yml
              path: "{{ base .Values.go_backend.configmap.data.TRAEFIK_TEMPLATE }}"

