apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-backend
    spec:
      initContainers:
      - command:
        - sh
        - -c
        - ../server -seed /opt/seed.yaml
        envFrom:
        - configMapRef:
            name: go-backend-conf
            optional: false
        image: {{ template "go_backend_image" . }}
        imagePullPolicy: {{ .Values.go_backend.deployment.image.pullPolicy }}
        name: init-seed
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/seed.yaml
          name: seed-config
          subPath: seed.yaml
        - name: traefik-config
          mountPath: "{{ .Values.go_backend.configmap.data.TRAEFIK_TEMPLATE }}"
          subPath: "{{ base .Values.go_backend.configmap.data.TRAEFIK_TEMPLATE }}"
      containers:
      - args:
        - -migrate
        - -worker
        command:
        - /server
        envFrom:
        - configMapRef:
            name: go-backend-conf
            optional: false
        image: {{ template "go_backend_image" . }}
        imagePullPolicy: {{ .Values.go_backend.deployment.image.pullPolicy }}
        name: worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - envFrom:
        - configMapRef:
            name: go-backend-conf
            optional: false
        image: {{ template "go_backend_image" . }}
        imagePullPolicy: {{ .Values.go_backend.deployment.image.pullPolicy }}
        name: app
        args:
        - -migrate
        - -server
        command:
        - /server
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: go-backend-persistent-storage
        - name: traefik-config
          mountPath: "{{ .Values.go_backend.configmap.data.TRAEFIK_TEMPLATE }}"
          subPath: "{{ base .Values.go_backend.configmap.data.TRAEFIK_TEMPLATE }}"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: "{{ .Values.image.pullSecret }}"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: seed-config
        name: seed-config
      - hostPath:
          path: /opt/upload_data
          type: DirectoryOrCreate
        name: go-backend-persistent-storage
      - name: traefik-config
        configMap:
          name: traefik-template-conf
          items:
            - key: traefik_config_template.yml
              path: "{{ base .Values.go_backend.configmap.data.TRAEFIK_TEMPLATE }}"

