---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cfg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: tacgui
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  php-config: |
    <?php
    define('DB_NAME', '{{ .Values.externalDatabase.database }}');
    define('DB_NAME_LOG', '{{ .Values.externalDatabase.logDatabase }}');
    define('DB_USER', '{{ .Values.externalDatabase.user }}');
    define('DB_PASSWORD', '{{ .Values.externalDatabase.password }}');
    define('DB_HOST', '{{ .Values.externalDatabase.host }}');
    define('DB_CHARSET', 'utf8');
    define('DB_COLLATE', 'utf8_unicode_ci');
    define('TAC_ROOT_PATH', '/opt/tacacsgui');
    define('TAC_PLUS_CFG', '/opt/tacacsgui/tac_plus.cfg');
    define('TAC_PLUS_CFG_TEST', '/opt/tacacsgui/tac_plus.cfg_test');
    define('TAC_PLUS_PARSING', TAC_ROOT_PATH. '/tacTestOutput.txt');
    define('TAC_DEAMON', TAC_ROOT_PATH . '/tac_plus.sh');
    define('BACKUP_PATH', TAC_ROOT_PATH . '/backup/database/');

  default-vars: |
    MYSQL_HOST={{ .Values.externalDatabase.host }}