apiVersion: v1
kind: secret
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  config.yaml: |
{{ include "pnetlab-exporter.config.yaml" . | b64enc | indent 4 }}