{{- if and .Values.persistence .Values.persistence.enabled -}}

{{- if not .Values.persistence.dynamicProvisioning }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ include "mageai.fullname" . }}-logs
  labels:
    deployment: {{ include "mageai.fullname" . }}
spec:
  capacity:
    storage: {{ .Values.persistence.size}}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName}}
  {{- with .Values.persistence.csi }}
  csi:
    {{- toYaml . | nindent 4 }}
    volumeHandle: pv-{{ include "mageai.fullname" $ }}-logs
  {{- end }}

{{- end }}
{{- end }}
