{{- if and .Values.persistence .Values.persistence.enabled -}}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ include "mageai.fullname" . }}-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClassName}}-logs
  resources:
    requests:
      storage: {{ .Values.persistence.size}}
  {{- if not .Values.persistence.dynamicProvisioning }}
  selector:
    matchLabels:
      deployment: {{ include "mageai.fullname" . }}
  {{- end}}
  
{{- end }}
