{{- if and .Values.persistence .Values.persistence.enabled -}}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ include "mageai.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClassName}}
  resources:
    requests:
      storage: {{ .Values.persistence.size}}
  {{- if not .Values.persistence.dynamicProvisioning }}
  volumeName: pv-{{ include "mageai.fullname" . }}
  {{- end}}
  
{{- end }}
