
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mageai.secretName" . }}
  labels:
    {{- include "mageai.labels" . | nindent 4 }}
data:
{{ if and (not .Values.existingSecret) (.Values.secrets) }}
  {{- toYaml .Values.secrets | nindent 2 }}
{{ end }}
  user_github_repo: {{ .Values.global.github.user | b64enc | quote }}
  token: {{ .Values.global.github.token | b64enc | quote }}
  fg_token: {{ .Values.global.github.fg_token | b64enc | quote }}
