apiVersion: v2
annotations:
  category: Infrastructure
name: ingress-nginx
description: SVTECH ingress-nginx

dependencies:
  - name: common
    repository: https://vyvuvivo.github.io/SVTcharts/artifacthub/
    version: 1.x.x

version: 1.0.0
appVersion: "v1.0.0"
