apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: emqx
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/client_max_body_size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.global.enableHttps | quote }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .Values.global.enableHttps | quote }}
    nginx.ingress.kubernetes.io/preserve-trailing-slash: 'true'
spec:
  ingressClassName: {{ .Release.Name }}
  rules:
    - http:
        paths:
          - path: {{ .Values.mqtt.websocket.mqttPath }}
            pathType: Prefix
            backend:
              service:
                name: emqx-listeners
                port:
                  number: 8083
          - path: {{ .Values.mqtt.secureWebsocket.mqttPath }}
            pathType: Prefix
            backend:
              service:
                name: emqx-listeners
                port:
                  number: 8084
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-dashboard-ingress
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: emqx-dashboard
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.global.enableHttps | quote }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .Values.global.enableHttps | quote }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/preserve-trailing-slash: 'true'
spec:
  ingressClassName: {{ .Release.Name }}
  rules:
    - http:
        paths:
          - path: /{{ .Release.Name }}/emqx/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: emqx-dashboard
                port:
                  number: 18083
