apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |
    version: 0.1
    log:
      level: {{ .Values.registry.log.level | default "info" }}
    storage:
      cache:
        blobdescriptor: inmemory
      s3:
        bucket: {{ .Values.registry.s3.bucket }}
        accesskey: {{ .Values.registry.s3.accesskey }}
        secretkey: {{ .Values.registry.s3.secretkey }}
        region: {{ .Values.registry.s3.region | default "us-east-1" }}
        regionendpoint: http://{{ .Values.seaweedfs.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local:8333
        secure: {{ .Values.registry.s3.secure | default false }}
        v4auth: true
        rootdirectory: {{ .Values.registry.s3.rootdirectory | default "/" }}
        forcepathstyle: true
        chunksize: 134217728
        multipartcopythresholdsize: 1073741824
        multipartcopyChunksize: 134217728
        multipartcopyMaxConcurrency:  1
      redirect:
        disable: {{ .Values.registry.storage.redirect.disable | default false }}
    http:
      addr: :5000
      secret: "registry_key_2026"
      headers:
        X-Content-Type-Options: [nosniff]
