apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-create-bucket
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-bucket
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              mc alias set seaweedfs {{ .Values.seaweedfs.endpoint }} \
                {{ .Values.seaweedfs.accesskey }} \
                {{ .Values.seaweedfs.secretkey }}

              {{- range .Values.seaweedfs.buckets }}
              mc mb --ignore-existing seaweedfs/{{ . }}
              {{- end }}

