{{- if and (eq (.Values.registry.storageBackend | default "s3") "filesystem") .Values.registry.persistence.enabled (not .Values.registry.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-data" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: docker-registry
  {{- with .Values.registry.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.registry.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.registry.persistence.size }}
  {{- if .Values.registry.persistence.storageClassName }}
  storageClassName: {{ .Values.registry.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
