---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-storage" (include "common.names.fullname" .) }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: docker-registry
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: seaweedfs-storage
  resources:
    requests:
      storage: 6Gi