---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-service
spec:
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP

