global:
  imageRegistry: ghcr.io
  basePath: /opt/shared

ingress:
  enabled: true
  className: ""
  annotations: {}
  host: ""
  path: /bngblaster-gui
  pathType: Prefix
  tls: []

frontend:
  replicaCount: 1
  image:
    repository: "svtechnmaa/bngblaster-gui-frontend"
    tag: "v1.1.7"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources: {}

backend:
  replicaCount: 1
  image:
    repository: "svtechnmaa/bngblaster-gui-backend"
    tag: "v1.1.7"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  resources: {}
  secret:
    secretKey: ""
    fernetKey: ""
    googleClientId: ""
    googleClientSecret: ""
    googleRedirectUri: ""
    keycloakServerUrl: ""
    keycloakRealm: ""
    keycloakClientId: ""
    keycloakClientSecret: ""
    keycloakRedirectUri: ""

sharedVolume:
  volumeName: backend-data
  path: /app/app/data
  pvcName: backend-data-pvc
  storageSize: 2Gi
  accessModes: ReadWriteOnce
  storageClass: backend-data-hostpath

# Default mode uses an external PostgreSQL database.
# Fill these values to point the backend to your existing PostgreSQL service.
externalPostgresql:
  host: ""
  port: 5432
  username: ""
  password: ""
  database: ""
