{{- $namespace := .Release.Namespace }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sharedVolume.pvcName }}

spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ $namespace }}-{{ .Values.sharedVolume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.sharedVolume.storageSize }}
