global:
  imageRegistry: ""

image:
  registry: docker.io
  repository: registry
  tag: 2.6
  pullPolicy: IfNotPresent

registry:
  log:
    level: info
  s3:
    bucket: registry
    region: us-east-1
    secure: false
    rootdirectory: /
    accesskey: ""
    secretkey: ""
  storage:
    redirect:
      disable: false

seaweedfs:
  serviceName: seaweedfs-s3

