---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ingress-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
{{- if .Values.ingress_nginx_configmap }}
data:
  {{- range $key, $value := .Values.ingress_nginx_configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
