apiVersion: batch/v1
kind: Job
metadata:
  name: init-report-fe
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - command:
        - bash
        - -ec
        - |
          if [ ! -f /usr/share/nginx/html/completed ]; then
            echo "Starting Reflex frontend initialization..."
            mkdir -p /usr/share/nginx/html
            sed -i '
            s/frontend_path="[^"]*"/frontend_path=os.environ["FRONTEND_PATH"]/
            s/frontend_packages=\[[^]]*\]/&,\n    api_url=os.environ["API_URL"]/
            ' rxconfig.py
            cat rxconfig.py
            {{- if not (empty .Values.backend.config.basehref) }}
            grep -rl "/report/logo" | xargs sed -i "s|/report/logo|{{ .Values.backend.config.basehref }}/report/logo|g"
            {{- end }}
            reflex export --frontend-only --no-zip
            cp -r .web/_static/* /usr/share/nginx/html/
            if [ $? -eq 0 ]; then
              echo "True" > /usr/share/nginx/html/completed
            fi
          else
            echo "Reflex frontend already initialized."
          fi
        image: {{ include "common.images.image" ( dict "imageRoot" .Values.frontend.initJob.image "global" .Values.global) }}
        {{- if .Values.frontend.initJob.image.pullPolicy }}
        imagePullPolicy: {{ .Values.frontend.initJob.image.pullPolicy }}
        {{- end }}
        env:
          {{- if not (empty .Values.global.http_proxy) }}
          - name: HTTP_PROXY
            value: http://{{ .Values.global.http_proxy }}
          - name: HTTPS_PROXY
            value: http://{{ .Values.global.http_proxy }}
          {{- end }}
        name: init-report-fe
        volumeMounts:
        - mountPath: /app/.env
          name: report-ui-env
          subPath: .env
        {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
        {{- range .Values.global.sharedPersistenceVolume }}
        {{- if has "report-ui" .shareFor }}
        - name: {{ .volumeName }}
          mountPath: {{ .path }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
      volumes:
      - secret:
          defaultMode: 420
          secretName: {{ include "common.names.fullname" . }}-env
        name: report-ui-env
      {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
      {{- range .Values.global.sharedPersistenceVolume }}
      {{- if has "report-ui" .shareFor }}
      - name: {{ .volumeName }}
        persistentVolumeClaim:
          claimName: {{ .pvcName }}
      {{- end }}
      {{- end }}
      {{- end }}
      restartPolicy: Never
