{{- $basehref := .Values.backend.config.basehref | default "" -}}
{{- $reportPath := printf "%s/report" $basehref -}}
{{- $grafanaReportPath := printf "%s/report/grafana" $basehref -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-fe-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-path: "{{ $reportPath }}/"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($uri = "{{ $reportPath }}") {
        return 308 https://$http_host{{ $reportPath }}/$is_args$args;
      }
spec:
  ingressClassName: {{ .Release.Name }}
  rules:
  - http:
      paths:
      # Main application path
      - path: "{{ $reportPath }}(/(?!grafana(/|$)).*)?$"
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: {{ .Values.backend.service.port }}
              
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-GRAFANA-USER "$cookie_ref_grafana_user";
      proxy_set_header X-GRAFANA-HOSTGROUP "$cookie_ref_grafana_hostgroup";
      proxy_set_header X-GRAFANA-ORGID "$cookie_ref_grafana_orgId";
      set $report_grafana_api 0;
      if ($http_referer ~ "^https?://[^/]+{{ $grafanaReportPath }}/") {
        set $report_grafana_api 1;
      }
      set $report_grafana_auth "$report_grafana_api:$cookie_ref_grafana_session";
      if ($report_grafana_auth = "1:") {
        return 401;
      }
  name: {{ .Chart.Name }}-be-ingress
spec:
  ingressClassName: {{ .Release.Name }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: {{ .Values.backend.service.port }}
        path: "{{ $basehref }}/(_event|ping|_upload|_health|graphql|pingtrace)(/.*)?$"
        pathType: ImplementationSpecific
