apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}-frontend
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.fullname" . }}-frontend
spec:
  replicas: {{ include "common.replicas" ( dict "replicaCount" .Values.frontend.replicaCount "global" .Values.global ) }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/componen: report-ui-frontend
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/componen: report-ui-frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: {{ include "common.images.image" (dict "imageRoot" .Values.frontend.init.image) }}
          imagePullPolicy: {{ .Values.frontend.init.image.pullPolicy | quote }}
          command:
            - /bin/sh
            - -c
            - |
              until nc -zvw5 {{ .Chart.Name }}-backend 8000; do echo "Waiting for Backend..."; sleep 2; done
      containers:
      - image: {{ include "common.images.image" ( dict "imageRoot" .Values.frontend.image "global" .Values.global) }}
        {{- if .Values.frontend.image.pullPolicy }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        {{- end }}
        name: reflex-frontend
        # command:
        #   - bash
        #   - -ec
        #   - |
        #     reflex run --env prod --frontend-only --frontend-port 3000
        env:
          - name: TZ
            value: {{ include "common.timezone" ( dict "timezone" .Values.timezone "global" .Values.global) }}
          # - name: HTTP_PROXY
          #   value: http://10.121.6.43:3128 
          # - name: HTTPS_PROXY
          #   value: http://10.121.6.43:3128
          # - name: NO_PROXY
          #   value: "lb-apiserver.kubernetes.local, 10.121.30.177,10.121.30.173,pe-nms01,pe-nms01.cluster.local,10.121.30.174,pe-nms02,pe-nms02.cluster.local,10.121.30.175,pe-nms03,pe-nms03.cluster.local,10.121.30.176,pe-nms04,pe-nms04.cluster.local,127.0.0.1,localhost,192.168.99.0/24,192.168.100.0/24,svc,svc.cluster.local,grafana"
        ports:
        - containerPort: 80
          name: frontend
        # volumeMounts:
        # - name: report-ui-env
        #   mountPath: /app/.env
        #   subPath: .env
      #   readinessProbe:
      #     failureThreshold: 3
      #     httpGet:
      #       path: /report
      #       port: 3000
      #       scheme: HTTP
      #     initialDelaySeconds: 60
      #     periodSeconds: 10
      #     successThreshold: 1
      #     timeoutSeconds: 5
      # volumes:
      # - name: report-ui-env
      #   configMap:
      #     name: report-ui-env
      imagePullSecrets:
      - name: ghcr-pull-secret
