apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: {{ .Chart.Name }}-backend
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ .Chart.Name }}-backend
spec:
  type:  {{ .Values.backend.service.type }}
  {{- if and (eq .Values.backend.service.type "LoadBalancer") (not (empty .Values.backend.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.backend.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.backend.service.type "LoadBalancer") .Values.backend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.backend.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if and (eq .Values.backend.service.type "ClusterIP") .Values.backend.service.clusterIP }}
  clusterIP: {{ .Values.backend.service.clusterIP }}
  {{- end }}
  ports:
    - name: backend
      port: {{ .Values.backend.service.port }}
      protocol: TCP
      targetPort: backend
      {{- if eq .Values.backend.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector:
    app.kubernetes.io/component: report-ui-backend
    {{- include "common.labels.matchLabels" . | nindent 4 }}
  