apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}-worker
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.fullname" . }}-worker
spec:
  replicas: {{ include "common.replicas" ( dict "replicaCount" .Values.worker.replicaCount "global" .Values.global) }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Chart.Name }}-worker
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Chart.Name }}-worker
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      containers:
      - image: {{ include "common.images.image" ( dict "imageRoot" .Values.worker.image "global" .Values.global) }}
        {{- if .Values.worker.image.pullPolicy }}
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        {{- end }}
        name: worker
        command:
        - bash
        - -ec
        - |
          export $(grep -v '^#' /app/.env | xargs)
          rq worker --with-scheduler --url redis://$REDIS_HOST:$REDIS_PORT
        env:
          - name: TZ
            value: {{ include "common.timezone" ( dict "timezone" .Values.timezone "global" .Values.global) }}
          - name: REDIS_HOST
            value: {{ .Chart.Name }}-redis
          - name: REDIS_PORT
            value: {{ .Values.redis.service.port | quote }}
        volumeMounts:
        - name: report-ui-env
          mountPath: /app/.env
          subPath: .env
      volumes:
      - name: report-ui-env
        secret:
          secretName: {{ include "common.names.fullname" . }}-env
      imagePullSecrets:
      - name: ghcr-pull-secret
