apiVersion: apps/v1
kind: Deployment
metadata:
  name: asynqmon
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asynqmon
  template:
    metadata:
      labels:
        app: asynqmon
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: go-backend-conf
            optional: false
        image: {{ template "asynqmon_image" . }}
        imagePullPolicy: Always
        name: asynqmon
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghcrio
      restartPolicy: Always
