
#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=INFO
rdeck.base=/home/rundeck

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false

# Bind address and server URL
server.address=0.0.0.0
server.servlet.context-path=/rundeck
grails.serverURL=http://rundeck:4440/rundeck
rundeck.multiURL.enabled=true

server.servlet.session.timeout=3600


dataSource.url = jdbc:h2:file:/home/rundeck/server/data/grailsdb;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=MONTH,HOUR,MINUTE,YEAR,SECONDS
dataSource.username = 
dataSource.password = 


#Pre Auth mode settings
rundeck.security.authorization.preauthenticated.enabled=false
rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS
rundeck.security.authorization.preauthenticated.delimiter=,
# Header from which to obtain user name
rundeck.security.authorization.preauthenticated.userNameHeader=X-Forwarded-Uuid
# Header from which to obtain list of roles
rundeck.security.authorization.preauthenticated.userRolesHeader=X-Forwarded-Roles
# Redirect to upstream logout url
rundeck.security.authorization.preauthenticated.redirectLogout=false
rundeck.security.authorization.preauthenticated.redirectUrl=/oauth2/sign_in
# user sync
rundeck.security.authorization.preauthenticated.userSyncEnabled=false
rundeck.security.authorization.preauthenticated.userFirstNameHeader=X-Forwarded-User-FirstName
rundeck.security.authorization.preauthenticated.userLastNameHeader=X-Forwarded-User-LastName
rundeck.security.authorization.preauthenticated.userEmailHeader=X-Forwarded-User-Email


rundeck.api.tokens.duration.max=0

rundeck.log4j.config.file=/home/rundeck/server/config/log4j.properties

rundeck.gui.startpage=projectHome

rundeck.clusterMode.enabled=true




rundeck.metrics.enabled=false
rundeck.metrics.jmxEnabled=false
rundeck.security.httpHeaders.enabled=true

rundeck.security.httpHeaders.provider.xcto.enabled=true

rundeck.security.httpHeaders.provider.xxssp.enabled=true

rundeck.security.httpHeaders.provider.xfo.enabled=true

rundeck.security.httpHeaders.provider.csp.enabled=true

rundeck.security.httpHeaders.provider.csp.config.include-xcsp-header=false

rundeck.security.httpHeaders.provider.csp.config.include-xwkcsp-header=false






rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=keys

rundeck.projectsStorageType=db


