global:
  sharedVolume:
    enabled: false
  externalIP: "" # externalIP for CICD

timezone: Asia/Ho_Chi_Minh

init:
  image:
    registry: docker.io
    repository: busybox
    tag: 1.33

    pullPolicy: IfNotPresent

image:
  repository: svtechnmaa/svtech_rundeck_option_provider
  tag: v1.1.1

  pullPolicy: IfNotPresent
  # debug: true

clusterDomain: cluster.local
commonAnnotations:
  helm.sh/hook-weight: "0"
commonLabels: {}

replicaCount: 2

updateStrategy: RollingUpdate
podManagementPolicy: OrderedReady
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  ## Node affinity type
  ## Allowed values: soft, hard
  type: ""
  ## Node label key to match
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  ## Node label values to match
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []


## Affinity for pod assignment
## Note: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
##
affinity: {}

## Node labels for pod assignment
nodeSelector: {}

## Tolerations for pod assignment
tolerations: []

## Extra volumes to add to the deployment
extraVolumes: []

## Extra volume mounts to add to the container
extraVolumeMounts: []

securityContext:
  enabled: false
  fsGroup: 0
  runAsUser: 0

resources:
  limits: {}
  #   cpu: 100m
  #   memory: 128Mi
  requests: {}
  #   cpu: 100m
  #   memory: 128Mi


livenessProbe:
  enabled: false
  initialDelaySeconds: 180
  periodSeconds: 45
  timeoutSeconds: 30
  successThreshold: 1
  failureThreshold: 6
readinessProbe:
  enabled: false
  initialDelaySeconds: 60
  periodSeconds: 45
  timeoutSeconds: 30
  successThreshold: 1
  failureThreshold: 6

## Custom Liveness probe
customLivenessProbe: {}

## Custom Readiness probe
customReadinessProbe: {}

## Container ports
containerPorts:
  # icinga2Api: 5665
  # livestatus: 6558

service:
  ## Service type
  ##
  type: ClusterIP
  port: 1111

  # loadBalancerIP:
  # loadBalancerSourceRanges:
  # - 10.10.10.0/24

  # externalIPs: ["10.98.0.143"]

  ## Set the Cluster IP to use
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address
  ##
  # clusterIP: None
  ## Provide any additional annotations which may be required
  ##
  annotations: {}
  ## Set the service SessionAffinity for session stickiness
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-userspace
  sessionAffinity: ClientIP

  # ## Customize the SessionAffinity configuration. The default value for sessionAffinityConfig.clientIP.timeoutSeconds is 10800 (3 hours)
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 7200

datasources: |-
  - name: Influxdb
    type: influxdb
    host: influxdb
    port: 8086
    username: juniper
    password: juniper@123

  - name: Livestatus
    type: livestatus
    host: icinga2
    port: 6558

  - name: Icinga2
    type: icinga2
    host: icinga2
    port: 5665
    username: icingaAdmin
    password: icingaAdmin

  - name: Mariadb
    type: mariadb
    host: mariadb
    port: 3306
    username: rundeck_option_api
    password: juniper@123

  - name: Nagvis
    type: nagvis
    host: icinga2
    port: 6558
    backend_name: NMS
    backend_id: NMS
    backend_type: mklivestatus
