apiVersion: v1
kind: Secret
metadata:
  name: django-db-secret
  labels:
    app: django
stringData:
  DB_NAME: {{ .Values.db.name | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
type: Opaque
