apiVersion: v1
kind: Secret
metadata:
  name: django-db-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: django
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
stringData:
  DB_NAME: {{ .Values.db.name | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
type: Opaque
