apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.frontendDist.claimName }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.frontendDist.size }}
  storageClassName: {{ .Values.pvc.frontendDist.storageClass }}