{{- if .Values.global.speedtest.runInitDataJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: init-data-job
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: init-data
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: init-data
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- with .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-mariadb
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image.initWaitDb "global" .Values.global) }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          command:
            - /bin/sh
            - -c
            - |
              until nc -zvw5 {{ .Values.db.host }} 3306; do echo "Waiting for MariaDB..."; sleep 2; done

      containers:
        - name: migrate
          image: {{ include "common.images.image" (dict "imageRoot" .Values.image.django "global" .Values.global) }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          command: [ "python", "manage.py", "init_data" ]
          env:
            - name: DB_ENGINE
              value: {{ .Values.django.dbEngine | quote }}
            - name: DJANGO_SUPERUSER_USERNAME
              value: {{ .Values.django.superUserUsername | quote }}
            - name: DJANGO_SUPERUSER_EMAIL
              value: {{ .Values.django.superUserEmail | quote }}
            - name: DJANGO_SUPERUSER_PASSWORD
              value: {{ .Values.django.superUserPassword | quote }}
            - name: TEST_SERVER_HOST
              value: {{ .Values.global.frontendVip | quote }}
            - name: TEST_SERVER_URL_BASE
              value: {{ .Values.paths.speedtestServer | quote }}
            - name: ENABLE_HTTPS
              value: {{ .Values.global.enableHttps | quote }}
          envFrom:
            - secretRef:
                name: django-db-secret
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
