apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.static.claimName }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.static.size }}
  storageClassName: {{ .Values.pvc.static.storageClass }}