{{- if .Values.netforgeAppSecretEnv }}
{{- $netforgeAppSecretName := printf "%s-secret-env" .Chart.Name | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $netforgeAppSecretName }}
type: Opaque
data:
  {{- range $key, $val := .Values.netforgeAppSecretEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
