{{- if .Values.conductor.enabled }}
{{- $conductorWorkerName := printf "%s-conductor-worker" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- $netforgeAppConfigMapName := printf "%s-env" .Chart.Name | trunc 63 | trimSuffix "-" }}
{{- $netforgeAppSecretName := printf "%s-secret-env" .Chart.Name | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $conductorWorkerName }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ $conductorWorkerName }}
spec:
  replicas: {{ .Values.conductorWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $conductorWorkerName }}
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: {{ $conductorWorkerName }}
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "netforge-be.repoWaitInitContainer" . | nindent 8 }}
      containers:
        - name: conductor-worker
          securityContext:
            capabilities:
              add:
                - NET_RAW
          image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - python -m app.conductor_worker
          env:
            - name: TZ
              value: {{ include "common.timezone" (dict "timezone" .Values.timezone "global" .Values.global) }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if or .Values.netforgeAppEnv .Values.netforgeAppSecretEnv }}
          envFrom:
            {{- if .Values.netforgeAppEnv }}
            - configMapRef:
                name: {{ $netforgeAppConfigMapName }}
            {{- end }}
            {{- if .Values.netforgeAppSecretEnv }}
            - secretRef:
                name: {{ $netforgeAppSecretName }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.conductorWorker.resources | nindent 12 }}
          volumeMounts:
            {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
            {{- range .Values.global.sharedPersistenceVolume }}
            {{- if has $.Chart.Name .shareFor }}
            - name: {{ .volumeName }}
              mountPath: {{ .path }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
        {{- range .Values.global.sharedPersistenceVolume }}
        {{- if has $.Chart.Name .shareFor }}
        - name: {{ .volumeName }}
          persistentVolumeClaim:
            claimName: {{ .pvcName }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
{{- end }}
