{{- if .Values.conductor.enabled }}
{{- $conductorConfigName := printf "%s-conductor-config" .Release.Name | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $conductorConfigName }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  config.properties: |
    {{- default (.Files.Get "config/conductor/config.properties") .Values.conductor.configProperties | nindent 4 }}
{{- end }}
