{{- if and .Values.conductor.enabled .Values.conductorSecretEnv }}
{{- $conductorSecretName := printf "%s-conductor-secret-env" .Chart.Name | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $conductorSecretName }}
type: Opaque
data:
  {{- range $key, $val := .Values.conductorSecretEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
