apiVersion: apps/v1
kind: Deployment
metadata:
  name: conductor
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: conductor
spec:
  replicas: {{ .Values.conductor.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: conductor
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: conductor
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: conductor
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "common.images.image" (dict "imageRoot" .Values.conductor.image) }}
          imagePullPolicy: {{ .Values.conductor.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ include "common.timezone" (dict "timezone" .Values.timezone "global" .Values.global) }}
            - name: CONFIG_PROP
              value: config.properties
          envFrom:
            - secretRef:
                name: conductor-secret-env
          ports:
            {{- range .Values.conductor.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          resources:
            {{- toYaml .Values.conductor.resources | nindent 12 }}
          volumeMounts:
            - name: conductor-config
              mountPath: /app/config/config.properties
              subPath: config.properties
              readOnly: true
      volumes:
        - name: conductor-config
          configMap:
            name: conductor-config
