{{- if .Values.conductor.enabled }}
{{- $conductorWorkerName := printf "%s-conductor-worker" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- $conductorWorkerHeadlessServiceName := printf "%s-conductor-worker-headless" (include "common.names.name" .) | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $conductorWorkerHeadlessServiceName }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ $conductorWorkerName }}
spec:
  clusterIP: None
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $conductorWorkerName }}
{{- end }}
