{{- if and .Values.conductor.enabled .Values.conductorEnv }}
{{- $conductorConfigMapName := printf "%s-conductor-env" .Chart.Name | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $conductorConfigMapName }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.conductorEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- if .Values.conductor.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-conductor-config" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  config.properties: |
    {{- default (.Files.Get "config/conductor/config.properties") .Values.conductor.configProperties | nindent 4 }}
{{- end }}
