apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }} # replace if needed
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ include "common.replicas" ( dict "replicaCount" .Values.replicaCount "global" .Values.global ) }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Chart.Name }} # replace if needed
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Chart.Name }} # replace if needed
    spec:
      # Allocate pods to nodes
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}

      imagePullSecrets:
      - name: ghcr-pull-secret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      initContainers:
      - name: init-repo
        image: {{ include "common.images.image" (dict "imageRoot" .Values.initRepo.image "global" .Values.global) }}
        imagePullPolicy: {{ .Values.initRepo.pullPolicy | quote }}
        command:
          - bash
          - -ec
          - |
            name=`echo $REPO | sed  "s/:.*//"`
            mkdir -p $REPO_PATH
            status=`ls -A $REPO_PATH | grep -v ".stfolder" | wc -l`
            if [[ "$status" == "0" ]]; then
              echo "$REPO_PATH is Empty. Clone repo"
              git clone --branch $BRANCH https://$GH_USER:$GH_FG_TOKEN@github.com/svtechnmaa/$name.git $REPO_PATH
              echo "true" > $REPO_PATH/completed
            else
              if [[ ! -f "$REPO_PATH/completed" ]]; then
                check_branch=`git branch | grep -e '*'`
                if [[ "$check_branch" != "* $BRANCH" ]]; then
                  echo "Branch is not $BRANCH. Checkout"
                  git checkout $BRANCH
                fi
                echo "true" > $REPO_PATH/completed
              fi
              echo "$REPO_PATH is not Empty. Ignore"
            fi
        env:
          - name: GH_FG_TOKEN
            valueFrom:
              secretKeyRef:
                name: netforge-secret
                key: fg_token
          - name: GH_USER
            valueFrom:
              secretKeyRef:
                name: netforge-secret
                key: user
          - name: BRANCH
            value: main
          - name: REPO
            value: netforge
          - name: REPO_PATH
            value: /opt/netforge
        {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
        volumeMounts:
          {{- range .Values.global.sharedPersistenceVolume }}

          {{- if has $.Chart.Name .shareFor }}
          - name: {{ .volumeName }}
            mountPath: {{ .path }}
          {{- end }}

          {{- end }}
        {{- end }}

      # Containers config
      containers:
        # Server container
        - name: {{ .Chart.Name }} # replace if needed
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          # set to image: {{ include "common.images.image" ( dict "imageRoot" .Values.image ) }} if using docker.io as registry
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          # command:
          env:
            - name: TZ
              value: {{ include "common.timezone" ( dict "timezone" .Values.timezone "global" .Values.global) }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: netforge-be-env
            - secretRef:
                name: netforge-be-secret-env

          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            # shareVolume: VolumeMount
            {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
            {{- range .Values.global.sharedPersistenceVolume }}
            {{- if has $.Chart.Name .shareFor }}
            - name: {{ .volumeName }}
              mountPath: {{ .path }}
            {{- end }}
            {{- end }}
            {{- end }}
            # unshareVolume(volumeMount): define in the chart's values.yaml
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}

        # Worker container
        - name: celery-worker # replace if needed
          securityContext:
            capabilities:
              add:
                - NET_RAW
          # set to image: {{ include "common.images.image" ( dict "imageRoot" .Values.image ) }} if using docker.io as registry
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              celery -A app.core.celery_app worker \
              --loglevel=info \
              --pool=threads \
              --concurrency=16 \
              -Q device_ops,audit,scheduled,workflows
          env:
            - name: TZ
              value: {{ include "common.timezone" ( dict "timezone" .Values.timezone "global" .Values.global) }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: netforge-be-env
            - secretRef:
                name: netforge-be-secret-env

          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            # shareVolume: VolumeMount
            {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
            {{- range .Values.global.sharedPersistenceVolume }}
            {{- if has $.Chart.Name .shareFor }}
            - name: {{ .volumeName }}
              mountPath: {{ .path }}
            {{- end }}
            {{- end }}
            {{- end }}
            # unshareVolume(volumeMount): define in the chart's values.yaml
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
        

        # Scheduler container
        - name: celery-beat # replace if needed
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          # set to image: {{ include "common.images.image" ( dict "imageRoot" .Values.image ) }} if using docker.io as registry
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              celery -A app.core.celery_app beat --loglevel=info
          env:
            - name: TZ
              value: {{ include "common.timezone" ( dict "timezone" .Values.timezone "global" .Values.global) }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: netforge-be-env
            - secretRef:
                name: netforge-be-secret-env

          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            # shareVolume: VolumeMount
            {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
            {{- range .Values.global.sharedPersistenceVolume }}
            {{- if has $.Chart.Name .shareFor }}
            - name: {{ .volumeName }}
              mountPath: {{ .path }}
            {{- end }}
            {{- end }}
            {{- end }}
            # unshareVolume(volumeMount): define in the chart's values.yaml
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
        # Monitor container
        - name: flower # replace if needed
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          # set to image: {{ include "common.images.image" ( dict "imageRoot" .Values.image ) }} if using docker.io as registry
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.flower.image ) }}
          imagePullPolicy: {{ .Values.flower.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              celery \
              --broker=$CELERY_BROKER_URL \
              flower \
              --port=5555 \
              --basic-auth=$FLOWER_BASIC_AUTH \
              --persistent=true \
              --db=/data/flower.db 
          env:
            - name: TZ
              value: {{ include "common.timezone" ( dict "timezone" .Values.timezone "global" .Values.global) }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: netforge-be-env
            - secretRef:
                name: netforge-be-secret-env

          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            # shareVolume: VolumeMount
            {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
            {{- range .Values.global.sharedPersistenceVolume }}
            {{- if has $.Chart.Name .shareFor }}
            - name: {{ .volumeName }}
              mountPath: {{ .path }}
            {{- end }}
            {{- end }}
            {{- end }}
            - name: flower-data
              mountPath: /data
            # unshareVolume(volumeMount): define in the chart's values.yaml
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}

      volumes:
      # shareVolume(volume): define in the global values
        {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
        {{- range .Values.global.sharedPersistenceVolume }}
        {{- if has $.Chart.Name .shareFor }}
        - name: {{ .volumeName }}
          persistentVolumeClaim:
            claimName: {{ .pvcName }}
        {{- end }}
        {{- end }}
        {{- end }}
      # unshareVolume(volume): define in the chart's values.yaml
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
        - name: flower-data
          persistentVolumeClaim:
            claimName: flower-data