{{- if .Values.netforgeAppSecretEnv }}
{{- $netforgeAppSecretName := printf "%s-secret-env" .Chart.Name | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $netforgeAppSecretName }}
data:
  {{- range $key, $val := .Values.netforgeAppSecretEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if .Values.global.github }}
{{- $netforgeRepositorySecretName := printf "%s-secret" .Chart.Name | trunc 63 | trimSuffix "-" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $netforgeRepositorySecretName }}
type: Opaque
data:
  user: {{ .Values.global.github.user | b64enc | quote }}
  token: {{ .Values.global.github.token | b64enc | quote }}
  fg_token: {{ .Values.global.github.fg_token | b64enc | quote }}
{{- end }}
