{{ $workloadType := .Values.rebalance.workloadType }}
{{- $timezone := "Asia/Ho_Chi_Minh" }}
{{- if and (hasKey .Values "global") (hasKey .Values.global "timezone") }}
{{- $timezone = .Values.global.timezone }}
{{- end }}
apiVersion: apps/v1
kind: {{ $workloadType | default "Deployment" }}
metadata:
  name: {{ include "common.names.fullname" . }}-rebalance
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: rebalance
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if eq $workloadType "StatefulSet" }}
  serviceName: {{ .Chart.Name }}-headless
  {{- end }}
  replicas: {{ include "common.replicas" ( dict "replicaCount" .Values.replicaCount "global" .Values.global ) }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: rebalance
  {{- if and (eq $workloadType "Deployment") .Values.strategy }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  {{- end }}
  {{- if and (eq $workloadType "StatefulSet") .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: rebalance
    spec:
      # Allocate pods to nodes
      {{- if .Values.rebalance.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.rebalance.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}

      imagePullSecrets:
      - name: ghcr-pull-secret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      # Init container
      {{- if .Values.init }}
      initContainers:
        - name: wait-icinga2-master
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.init.image ) }}
          imagePullPolicy: {{ .Values.init.image.pullPolicy | quote }}
          command:
            - /bin/sh
            - -c
            - |
              until nc -zvw5 {{ include "common.names.fullname" . }}-master-0.icinga2-headless.{{ .Release.Namespace }} 5665;
              do
                echo "Waiting for Icinga2 master...";
                sleep 2;
              done
      {{- end }}

      # Containers config
      containers:
        - name: icinga2-rebalance
          command:
            - bash
            - -ec
            - |
              git config --global user.name "icinga"
              git config --global user.email "icinga@localhost"
              touch /etc/icinga2/zones.d/master/zones.conf
              touch /etc/icinga2/zones.d/master/satellite.conf
              python3 /opt/SVTECH-Junos-Automation/module_utils/ICINGA2_DISCOVERY.py \
                --sts_name {{ .Release.Name }}-icinga2-satellite \
                --namespace {{ .Release.Namespace }} \
                --all_config_folder /etc/icinga2/zones.d/all_config \
                --discovery_folder /etc/icinga2/zones.d \
                --zone_prefix zone_satellite \
                --endpoint_prefix {{ .Release.Name }}-icinga2-satellite \
                --headless_service icinga2-satellite-headless \
                --master_sts_name {{ .Release.Name }}-icinga2-master \
                --master_zones_config /etc/icinga2/zones.d/master/zones.conf \
                --master_endpoints_config /etc/icinga2/zones.d/master/endpoints.conf \
                --master_constants_config /etc/icinga2/zones.d/master/constants.conf \
                --master_folder /etc/icinga2/zones.d/master \
                --master_zone_config_path /etc/icinga2/zones.d/master_zones.conf \
                --master_headless_service icinga2-headless \
                --checking_interval 60 \
                --waiting_time_after_rebalancing 300
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ default $timezone | quote }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            # shareVolume: VolumeMount
            {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
            {{- range .Values.global.sharedPersistenceVolume }}
            {{- if has "icinga2-rebalance" .shareFor }}
            - name: {{ .volumeName }}
              mountPath: {{ .path }}
            {{- end }}
            {{- end }}
            {{- end }}
            # unshareVolume(volumeMount): define in the chart's values.yaml
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}

      volumes:
      # shareVolume(volume): define in the global values
        {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
        {{- range .Values.global.sharedPersistenceVolume }}
        {{- if has "icinga2-rebalance" .shareFor }}
        - name: {{ .volumeName }}
          persistentVolumeClaim:
            claimName: {{ .pvcName }}
        {{- end }}
        {{- end }}
        {{- end }}
      # unshareVolume(volume): define in the chart's values.yaml
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}