{{ $workloadType := .Values.rebalance.workloadType }}
{{- $timezone := "Asia/Ho_Chi_Minh" }}
{{- if and (hasKey .Values "global") (hasKey .Values.global "timezone") }}
{{- $timezone = .Values.global.timezone }}
{{- end }}
apiVersion: apps/v1
kind: {{ $workloadType | default "Deployment" }}
metadata:
  name: {{ include "common.names.fullname" . }}-rebalance
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: rebalance
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if eq $workloadType "StatefulSet" }}
  serviceName: {{ .Chart.Name }}-headless
  {{- end }}
  replicas: {{ include "common.replicas" ( dict "replicaCount" .Values.rebalance.replicaCount "global" .Values.global ) }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: rebalance
  {{- if and (eq $workloadType "Deployment") .Values.rebalance.strategy }}
  strategy:
    {{- toYaml .Values.rebalance.strategy | nindent 4 }}
  {{- end }}
  {{- if and (eq $workloadType "StatefulSet") .Values.rebalance.updateStrategy }}
  updateStrategy:
    {{- toYaml .Values.rebalance.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: rebalance
    spec:
      # Allocate pods to nodes
      {{- if .Values.rebalance.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.rebalance.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.rebalance.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.rebalance.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.rebalance.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.rebalance.tolerations "context" $) | nindent 8 }}
      {{- end }}

      imagePullSecrets:
      - name: ghcr-pull-secret
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      # Init container
      {{- if .Values.init }}
      initContainers:
        - name: wait-icinga2-master
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.init.image ) }}
          imagePullPolicy: {{ .Values.init.image.pullPolicy | quote }}
          command:
            - /bin/sh
            - -c
            - |
              until nc -zvw5 {{ .Chart.Name }} 5665;
              do
                echo "Waiting for Icinga2 master...";
                sleep 2;
              done
      {{- end }}

      # Containers config
      containers:
        - name: icinga2-rebalance
          command:
            - bash
            - -ec
            - |
              git config --global user.name "icinga"
              git config --global user.email "icinga@localhost"
              python3 /opt/SVTECH-Junos-Automation/module_utils/icinga2_rebalance.py \
                --namespace {{ .Release.Namespace }} \
                --master-headless-service {{ .Chart.Name }}-headless \
                --satellite-headless-service {{ .Chart.Name }}-satellite-headless \
                --master-zones-file /etc/icinga2/zones.d/master_zones.conf \
                --satellite-zones-file /etc/icinga2/zones.d/master/satellite_zones.conf \
                --icinga2-zones-folder /etc/icinga2/zones.d/ \
                --all-hosts-folder /etc/icinga2/zones.d/all_config \
                --zone-prefix zone-satellite \
                --interval 60 \
                --loglevel INFO

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ $timezone | quote }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            # shareVolume: VolumeMount
            {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
            {{- range .Values.global.sharedPersistenceVolume }}
            {{- if has "icinga2-rebalance" .shareFor }}
            - name: {{ .volumeName }}
              mountPath: {{ .path }}
            {{- end }}
            {{- end }}
            {{- end }}
            # unshareVolume(volumeMount): define in the chart's values.yaml
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}

      volumes:
      # shareVolume(volume): define in the global values
        {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
        {{- range .Values.global.sharedPersistenceVolume }}
        {{- if has "icinga2-rebalance" .shareFor }}
        - name: {{ .volumeName }}
          persistentVolumeClaim:
            claimName: {{ .pvcName }}
        {{- end }}
        {{- end }}
        {{- end }}
      # unshareVolume(volume): define in the chart's values.yaml
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}