{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
stringData:
  icinga2-api-user: {{ .Values.secrets.icinga2ApiUser | quote }}
  icinga2-api-password: {{ .Values.secrets.icinga2ApiPassword | quote }}
  {{- with .Values.secrets.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}