apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: gitlist
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  strategy:
    type: {{ .Values.updateStrategy }}
    {{- if (eq "Recreate" .Values.updateStrategy) }}
    rollingUpdate: null
    {{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: gitlist
  replicas: {{ include "common.replicas" ( dict "replicaCount" .Values.replicaCount "global" .Values.global ) }}
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: gitlist
    spec:
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
      containers:
        - name: gitlist
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global ) }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
          {{- end }}
          command:
            - bash
            - -ec
            - |
                sed -i "s/memory_limit = 128M/memory_limit = ${PHP_MEMORY_LIMIT}/" /usr/local/etc/php/php.ini
                mkdir -p /opt/gitlist/backup_config
                check_exists=`ls -la /opt/gitlist/backup_config | grep .git | wc -l`

                if [ $check_exists == 0 ]; then
                  cd /opt/gitlist/backup_config
                  git init /opt/gitlist/backup_config
                  git config --global user.name "NMS"
                  git config --global user.email 'NMS@localhost'
                  echo 'Repository for backup Juniper devices' > /opt/gitlist/backup_config/README
                  echo 'Repository for backup Juniper devices' > /opt/gitlist/backup_config/.git/description
                  git add /opt/gitlist/backup_config/README
                  git commit -m initial
                fi

                FULL_NAME={{ template "common.names.fullname" . }}
                POD_INDEX=${POD_NAME: -1}
                replicaCount={{ .Values.replicaCount }}

                echo "" > /opt/gitlist/backup_config/.git/hooks/post-commit
                chmod 775 /opt/gitlist/backup_config/.git/hooks/post-commit
                echo "chown gitlist:gitlist /opt/gitlist -R" >> /opt/gitlist/backup_config/.git/hooks/post-commit
                echo "chmod 775 /opt/gitlist -R" >> /opt/gitlist/backup_config/.git/hooks/post-commit

                for ((i=0; i<$replicaCount; i++)); do
                  if [ $i != $POD_INDEX ]; then

                    full_pod_name="${FULL_NAME}-${i}.{{ template "common.names.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}"
                    command="sshpass -p 'juniper@123' rsync -e 'ssh -o StrictHostKeyChecking=no' -avh -O --delete --no-o --no-g --no-perms --exclude 'post-commit' /opt/gitlist gitlist@$full_pod_name:/opt"
                    echo $command >> /opt/gitlist/backup_config/.git/hooks/post-commit

                  fi
                done

                chown gitlist:gitlist /opt/gitlist -R
                chmod 775 /opt/gitlist -R

                service ssh start
                exec apache2-foreground

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TZ
              value: {{ include "common.timezone" ( dict "timezone" .Values.timezone "global" .Values.global) }}
            - name: PHP_MEMORY_LIMIT
              value: {{ .Values.env.PHP_MEMORY_LIMIT | quote }}

          ports:
            - name: gitlist
              containerPort: 80
            - name: rsync
              containerPort: 22

      {{- if and .Values.global.sharedPersistenceVolume .Values.global.sharedVolume.enabled }}
          volumeMounts:
            {{- range .Values.global.sharedPersistenceVolume }}

            {{- if has "gitlist" .shareFor }}
            - name: {{ .volumeName }}
              mountPath: {{ .path }}
            {{- end }}

            {{- end }}

      imagePullSecrets:
      - name: ghcr-pull-secret

      volumes:
        {{- range .Values.global.sharedPersistenceVolume }}

        {{- if has "gitlist" .shareFor }}
        - name: {{ .volumeName }}
          persistentVolumeClaim:
            claimName: {{ .pvcName }}
        {{- end }}

        {{- end }}

      {{- end  }}
