apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: {{ .Values.namespace }}
spec:
  ports:
  {{- range .Values.traefik.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}
  selector:
    app: traefik
  type: {{ .Values.traefik.service.type }}
  loadBalancerIP: {{ .Values.traefik.service.loadBalancerIP }}
