# apiVersion: v1
# kind: Secret
# metadata:
#   name: selfsignedcert
#   namespace: {{ .Values.namespace }}
# type: Opaque
# data:
#   tls.key:
# {{- include "traefik.tls.key" . | b64enc | indent 1 }}
#   tls.crt:
# {{- include "traefik.tls.crt" . | b64enc | indent 1 }}

