apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - args:
        - --providers.http.endpoint=http://go-backend/api/v1/traefik
        - --api.dashboard=true
        - --log.level=DEBUG
        - --entryPoints.web.address=:80
        - --entryPoints.web.asDefault=true
        - --entryPoints.websecure.address=:443
        - --entryPoints.websecure.asDefault=true
        - --entryPoints.traefik.address=:8080
        - --entrypoints.web.http.redirections.entryPoint.to=websecure
        - --entrypoints.web.http.redirections.entryPoint.scheme=https
        - --entrypoints.web.http.redirections.entrypoint.permanent=true
        image: {{ template "traefik_image" . }}
        imagePullPolicy: {{ .Values.traefik.deployment.image.pullPolicy }}
        name: traefik
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 8080
          name: traefik
          protocol: TCP
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /tls
          name: selfsignedcert
          readOnly: true
      volumes:
      - hostPath:
          path: {{ .Values.global.basePath}}/{{ .Release.Namespace }}/upload_data_newtopo
          type: DirectoryOrCreate
        name: selfsignedcert

        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
