apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-credentials
type: Opaque
stringData:
  {{- range .Values.global.clickhouse.users }}
  {{ .name }}_password_sha256_hex: "{{ .password | sha256sum }}"
  {{- end }}