{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bngblaster-gui.imagePullSecretName" . }}
  namespace: {{ include "bngblaster-gui.namespace" . | quote }}
  labels:
    {{- include "bngblaster-gui.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "bngblaster-gui.dockerConfigJson" . | b64enc | quote }}
{{- end }}
