{{- $externalPostgresql := default dict (index .Values "externalPostgresql") -}}
{{- $dbUsername := required "externalPostgresql.username is required" (index $externalPostgresql "username") -}}
{{- $dbPassword := required "externalPostgresql.password is required" (index $externalPostgresql "password") -}}
{{- $dbName := required "externalPostgresql.database is required" (index $externalPostgresql "database") -}}
{{- $dbPort := default 5432 (index $externalPostgresql "port") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bngblaster-gui.fullname" . }}-secret
  labels:
    {{- include "bngblaster-gui.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ required "backend.secret.secretKey is required" .Values.backend.secret.secretKey | quote }}
  FERNET_KEY: {{ required "backend.secret.fernetKey is required" .Values.backend.secret.fernetKey | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.backend.secret.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.backend.secret.googleClientSecret | quote }}
  GOOGLE_REDIRECT_URI: {{ .Values.backend.secret.googleRedirectUri | quote }}
  KEYCLOAK_SERVER_URL: {{ .Values.backend.secret.keycloakServerUrl | quote }}
  KEYCLOAK_REALM: {{ .Values.backend.secret.keycloakRealm | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.backend.secret.keycloakClientId | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.backend.secret.keycloakClientSecret | quote }}
  KEYCLOAK_REDIRECT_URI: {{ .Values.backend.secret.keycloakRedirectUri | quote }}
  POSTGRES_USER: {{ $dbUsername | quote }}
  POSTGRES_PASSWORD: {{ $dbPassword | quote }}
  POSTGRES_DB: {{ $dbName | quote }}
  DATABASE_URL: {{ printf "postgresql+psycopg2://%s:%s@%s:%d/%s" ($dbUsername | urlquery) ($dbPassword | urlquery) (include "bngblaster-gui.databaseHost" .) (int $dbPort) ($dbName | urlquery) | quote }}
