apiVersion: v2
annotations:
  category: icingaweb
name: icingaweb
engine: gotpl

dependencies:
  - name: common
    repository: https://vyvuvivo.github.io/SVTcharts/artifacthub/
    version: 1.x.x

version: 1.5.1
appVersion: "v1.0.0"
