apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-gdg-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: grafana
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  importer.yml: |
    {{- include "gdg.importer" . | nindent 4 }}
  {{- if .Values.gdgConfig.secureFiles }}
  {{- range $name, $config := .Values.gdgConfig.secureFiles }}
  {{ $name }}.json: {{ $config | toJson | quote }}
  {{- end }}
  {{- end }}
