{{- if not .Values.global.ci }}
---
# SA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-icinga-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-icinga-exec-role
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["*"]
    resources: ["pods/exec"]
    resourceNames: ["{{ .Release.Name }}-icinga2-master-0", "{{ .Release.Name }}-icinga2-master-1"]
    verbs: ["create"]  # Permissions needed to exec commands in pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-icinga-exec-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-icinga-exec-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-icinga-sa
    namespace: {{ .Release.Namespace }}
{{- end }}