apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: {{ .Release.Name }}-redis
  name: {{ .Release.Name }}-redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app.kubernetes.io/component: {{ .Release.Name }}-redis
  type: {{ .Values.redis.service.type }}
