apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: {{ .Release.Name }}-orchestrator
  name: {{ .Release.Name }}-orchestrator
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: {{ .Release.Name }}-orchestrator
  type: {{ .Values.orchestrator.service.type }}
