apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-redis
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}-redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}-redis
