{{- if .Values.netforgeYangSecretEnv }}
{{- $netforgeYangSecretName := printf "%s-secret-env" .Chart.Name | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $netforgeYangSecretName }}
data:
  {{- range $key, $val := .Values.netforgeYangSecretEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
