{{- if .Values.netforgeYangEnv }}
{{- $netforgeYangConfigMapName := printf "%s-env" .Chart.Name | trunc 63 | trimSuffix "-" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $netforgeYangConfigMapName }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.netforgeYangEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
