apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yang-db
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yang-uploads
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yang-device
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi