{{- if .Values.sharedPersistenceVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sharedPersistenceVolume.pvcName }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.sharedPersistenceVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.sharedPersistenceVolume.storageSize }}
  storageClassName: {{ .Values.sharedPersistenceVolume.storageClass }}
{{- end }}