apiVersion: v2
annotations:
  category: Backend
name: postfix
description: SVTECH Postfix
engine: gotpl

dependencies:
  - name: common
    repository: https://vyvuvivo.github.io/SVTcharts/artifacthub/
    version: 1.x.x

version: 1.2.0
appVersion: "v1.0.0"
