apiVersion: v2
annotations:
  category: kibana
name: kibana
description: kibana
engine: gotpl

dependencies:
  - name: common
    repository: https://vyvuvivo.github.io/SVTcharts/artifacthub/
    version: 1.x.x

version: 1.0.0
appVersion: "v1.0.0"
