apiVersion: v2
annotations:
  category: Storage
name: host-path-pv
description: SVTECH HostPath Persistent Volume
engine: gotpl

dependencies:
  - name: common
    repository: https://vyvuvivo.github.io/SVTcharts/artifacthub/
    version: 1.x.x

version: 1.1.1
appVersion: "v1.0.0"
