apiVersion: v2
annotations:
  category: Frontend
name: gitlist
description: SVTECH Gitlist
engine: gotpl

dependencies:
  - name: common
    repository: https://svtechnmaa.github.io/charts/artifacthub/
    version: 1.x.x

version: 1.1.2
appVersion: "v1.0.0"
