postgresql-ha: # Since we are using alias 'postgresql-ha' for the dependency
  enabled: true
  nameOverride: postgresql-ha
  postgresqlExternalHost: "postgresql-ha-pgpool" 
  postgresql:
    username: dummy
    password: "dummy@123"
    database: "default"
    repmgrUsername: dummy
    repmgrPassword: "dummy@123"
    repmgrDatabase: "repmgr"
    image:
      registry: ghcr.io
      repository: svtechnmaa/postgresql-repmgr
      tag: 14.5.0-debian-11-r19
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets:
        - ghcr-pull-secret
      ## Set to true if you would like to see extra information on logs
      ##
      debug: false
    replicaCount: 3
  pgpool:
    image:
      registry: ghcr.io
      repository: svtechnmaa/pgpool
      tag: 4.6.3-debian-12-r0
      digest: ""
      pullPolicy: IfNotPresent
      debug: false
      
  persistence:
    storageClass: postgresql-ha-postgresql
    accessModes:
      - ReadWriteOnce
    size: 3Gi
  volumePermissions:
    enabled: true
    image:
      registry: ghcr.io
      repository: svtechnmaa/os-shell
      tag: 11
      digest: ""
      pullPolicy: IfNotPresent


postgresql:
  enabled: false
  fullnameOverride: "postgresql-service"
  auth:
    username: dummy
    password: "dummy@123"
    database: "default"
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.2.0-debian-12-r3
    digest: ""
  persistence:
    storageClass: postgresql-standalone-postgresql
    accessModes:
      - ReadWriteOnce
    size: 3Gi
  primary:
    persistence:
      storageClass: postgresql-standalone-postgresql
      accessModes:
        - ReadWriteOnce
      size: 3Gi
  volumePermissions:
    enabled: true
    image:
      registry: ghcr.io
      repository: svtechnmaa/os-shell
      tag: 11
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets:
        - ghcr-pull-secret


persistence:
  # enabled: true
  size: 3Gi
  # dynamicProvisioning: false
  # # storageClassName: storage-class-share
  # storageClassName: seaweedfs-storage
  # csi:
  #   driver: seaweedfs-csi-driver
  # pathFolder: share
  hostPath: /data/postgresql-ha-postgresql

imagePullSecrets:
  - name: "ghcr-pull-secret"
nameOverride: ""
fullnameOverride: ""