postgresql-ha: # Since we are using alias 'postgresql-ha' for the dependency
  enabled: true
  nameOverride: postgresql-ha
  postgresqlExternalHost: "postgresql-ha-pgpool" 
  postgresql:
    username: dummy
    password: "dummy@123"
    database: "postgres"
    repmgrUsername: dummy
    repmgrPassword: "dummy@123"
    repmgrDatabase: "repmgr"
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
      readOnlyRootFilesystem: true
    extraVolumes:
      - name: postgresql-runtime
        emptyDir: {}
    extraVolumeMounts:
      - name: postgresql-runtime
        mountPath: /tmp
        subPath: tmp-dir
      - name: postgresql-runtime
        mountPath: /opt/bitnami/postgresql/conf
        subPath: postgresql-conf-dir
      - name: postgresql-runtime
        mountPath: /opt/bitnami/postgresql/tmp
        subPath: postgresql-tmp-dir
      - name: postgresql-runtime
        mountPath: /opt/bitnami/repmgr/conf
        subPath: repmgr-conf-dir
      - name: postgresql-runtime
        mountPath: /opt/bitnami/repmgr/tmp
        subPath: repmgr-tmp-dir
      - name: postgresql-runtime
        mountPath: /opt/bitnami/repmgr/logs
        subPath: repmgr-logs-dir
    image:
      registry: ghcr.io
      repository: svtechnmaa/postgresql-repmgr
      tag: 14.5.0-debian-11-r19
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets:
        - ghcr-pull-secret
      ## Set to true if you would like to see extra information on logs
      ##
      debug: false
    replicaCount: 3
    headlessWithNotReadyAddresses: true
  pgpool:
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
      readOnlyRootFilesystem: true
    extraVolumes:
      - name: pgpool-runtime
        emptyDir: {}
    extraVolumeMounts:
      - name: pgpool-runtime
        mountPath: /tmp
        subPath: tmp-dir
      - name: pgpool-runtime
        mountPath: /opt/bitnami/pgpool/etc
        subPath: pgpool-etc-dir
      - name: pgpool-runtime
        mountPath: /opt/bitnami/pgpool/conf
        subPath: pgpool-conf-dir
      - name: pgpool-runtime
        mountPath: /opt/bitnami/pgpool/tmp
        subPath: pgpool-tmp-dir
      - name: pgpool-runtime
        mountPath: /opt/bitnami/pgpool/logs
        subPath: pgpool-logs-dir
    image:
      registry: ghcr.io
      repository: svtechnmaa/pgpool
      tag: 4.6.3-debian-12-r0
      digest: ""
      pullPolicy: IfNotPresent
      debug: false
  metrics:
    podSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      
  persistence:
    storageClass: postgresql-ha-postgresql
    accessModes:
      - ReadWriteOnce
    size: 3Gi
  volumePermissions:
    enabled: true
    podSecurityContext:
      runAsUser: 0
      readOnlyRootFilesystem: true
    image:
      registry: ghcr.io
      repository: svtechnmaa/os-shell
      tag: 11
      digest: ""
      pullPolicy: IfNotPresent


postgresql:
  enabled: false
  fullnameOverride: "postgresql-service"
  auth:
    username: dummy
    password: "dummy@123"
    database: "default"
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.2.0-debian-12-r3
    digest: ""
  primary:
    persistence:
      storageClass: postgresql-standalone-postgresql
      accessModes:
        - ReadWriteOnce
      size: 3Gi
  volumePermissions:
    enabled: true
    image:
      registry: ghcr.io
      repository: svtechnmaa/os-shell
      tag: 11
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets:
        - ghcr-pull-secret


persistence:
  # enabled: true
  # dynamicProvisioning: false
  # # storageClassName: storage-class-share
  # storageClassName: seaweedfs-storage
  # csi:
  #   driver: seaweedfs-csi-driver
  # pathFolder: share
  hostPath: /data/postgresql-ha-postgresql

imagePullSecrets:
  - name: "ghcr-pull-secret"
nameOverride: ""
fullnameOverride: ""
