global:
  imageRegistry: ghcr.io
  imagePullSecrets: []

timezone: Asia/Ho_Chi_Minh

trivy:
  fullnameOverride: trivy-server
  replicaCount: 2
  image:
    registry: ghcr.io
    repository: svtechnmaa/trivy
    tag: "0.72.0"
    pullPolicy: IfNotPresent
  trivy:
    serverToken: ""
    cache:
      redis:
        enabled: true
        url: redis://trivy-server-redis:6379
        ttl: 24h

redis:
  replicaCount: 1
  image:
    repository: svtechnmaa/redis
    tag: "7.2.3"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
